USE NOTA_FISCAL_NORMALIZADA;


-- Forma clássica de consultas combinadas
-- Podemos definir ALIAS (apelidos) para as tabelas, facilitando a codificação (NF, IT)
SELECT
	NF.NRO_NOTA,
	NF.DT_EMISSAO,
	NF.VL_TOTAL,
	INF.COD_PRODUTO,
	P.DESC_PRODUTO,
	P.UN_MED,
	INF.QTD_PRODUTO,
	INF.VL_PRECO,
	INF.VL_TOTAL
FROM
	NOTA_FISCAL NF,
	ITEM_NOTA_FISCAL INF,
	PRODUTO P
WHERE
	NF.NRO_NOTA = INF.NRO_NOTA
	AND INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY 
	NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC
	;


-- Forma com JOINS
SELECT
	NF.NRO_NOTA,
	NF.DT_EMISSAO,
	NF.VL_TOTAL,
	INF.COD_PRODUTO,
	P.DESC_PRODUTO,
	P.UN_MED,
	INF.QTD_PRODUTO,
	INF.VL_PRECO,
	INF.VL_TOTAL
FROM
	NOTA_FISCAL NF
	INNER JOIN
		ITEM_NOTA_FISCAL INF
		ON NF.NRO_NOTA = INF.NRO_NOTA
	INNER JOIN
		PRODUTO P
			ON INF.COD_PRODUTO = P.COD_PRODUTO
WHERE 
	NF.NRO_NOTA = 4
ORDER BY 
	NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;




-- Quantas notas fiscais foram emitidas?
SELECT COUNT(*) FROM NOTA_FISCAL;


-- Notas fiscais por período
SELECT COUNT(*)
FROM NOTA_FISCAL
WHERE DT_EMISSAO > '2025-03-21'
AND DT_EMISSAO < '2025-03-25';

-- OU

SELECT COUNT(*)
FROM NOTA_FISCAL
WHERE DT_EMISSAO BETWEEN '2025-03-21' AND '2025-03-25'


-- Total de notas no ano
SELECT COUNT(*)
FROM NOTA_FISCAL
WHERE YEAR(DT_EMISSAO) = 2025;


-- MAX -> Obtendo o cliente que mais comprou determinado produto em uma única NF
SELECT 
	NF.NM_CLIENTE AS CLIENTE,
	P.DESC_PRODUTO AS PRODUTO,
	MAX(INF.QTD_PRODUTO) QTD
FROM ITEM_NOTA_FISCAL INF
INNER JOIN 
	NOTA_FISCAL NF 
		ON NF.NRO_NOTA = INF.NRO_NOTA
INNER JOIN 	
	PRODUTO P
		ON P.COD_PRODUTO = INF.COD_PRODUTO
GROUP BY  INF.COD_PRODUTO, NF.NM_CLIENTE
ORDER BY CLIENTE ASC, QTD DESC
;




