CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE NOTA_FISCAL_NORMALIZADA NFN;

CREATE TABLE NFN.NOTA_FISCAL (
	NRO_NOTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NM_CLIENTE VARCHAR(256) NOT NULL,
	END_CLIENTE VARCHAR(256) NOT NULL,
	NM_VENDEDOR VARCHAR(256) NOT NULL,
	DT_EMISSAO DATETIME DEFAULT CURRENT_TIMESTAMP,
	VL_TOTAL FLOAT NOT NULL	
);

CREATE TABLE NFN.PRODUTO (
	COD_PRODUTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESC_PRODUTO VARCHAR(256) NOT NULL,
	UN_MED CHAR (2) NOT NULL,
	VL_PRODUTO FLOAT NOT NULL
);

CREATE TABLE NFN.ITEM_NOTA_FISCAL (
	NRO_NOTA INT NOT NULL,
	COD_PRODUTO INT NOT NULL,
	QTD_PRODUTO FLOAT NOT NULL,
	VL_PRECO FLOAT NOT NULL,
	VL_TOTAL FLOAT NOT NULL,
	PRIMARY KEY (NRO_NOTA, COD_PRODUTO),
	CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL 
		FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL_NORMALIZADA.NOTA_FISCAL (NRO_NOTA),
		FOREIGN KEY (COD_PRODUTO) REFERENCES NOTA_FISCAL_NORMALIZADA.PRODUTO (COD_PRODUTO)		
);

INSERT INTO NOTA_FISCAL_NORMALIZADA.PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES 
	('Leite', 'LT', 4.50),
	('Desodorante', 'UN', 8.00),
	('Salame', 'KG', 40.00);

	
-- nota fiscal
	
INSERT INTO NOTA_FISCAL_NORMALIZADA.NOTA_FISCAL (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES 
	('Aragorn', 'Terra Média', 'Bilbo', 100.00),
	('Gandalf', 'Terra Média', 'Frodo', 100.00),
	('Boromir', 'Mordor', 'Sam', 100.00),
	('Galadriel', 'Valinor', 'Saruman', 100.00);
	
	
-- itens da nota
	
INSERT INTO NOTA_FISCAL_NORMALIZADA.ITEM_NOTA_FISCAL (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
VALUES 
	(1, 1, 1, 4.50, 4.50),
	(1, 2, 2, 40.00, 80.00),
	(1, 3, 10, 100.00, 1000.00),
	(2, 1, 1, 4.50, 4.50),
	(2, 2, 5, 40.00, 200.00),
	(2, 3, 3, 100.00, 300.00),
	(3, 1, 2, 4.50, 9.00),
	(3, 2, 3, 40.00, 120.00),
	(3, 3, 5, 100.00, 500.00),
	(4, 1, 1, 4.50, 4.50),
	(4, 2, 4, 40.00, 160.00),
	(4, 3, 7, 100.00, 700.00);

SELECT * FROM NOTA_FISCAL_NORMALIZADA.ITEM_NOTA_FISCAL;
	
	

-- UPDATE, ATUALIZANDO DADOS DE COLUNAS EM TABELAS
SELECT * FROM PRODUTO;
	
UPDATE PRODUTO 
SET VL_PRODUTO = 45
WHERE COD_PRODUTO = 3;

-- DELETE, EXCLUINDO REGISTROS DE TABELAS
SELECT * FROM PRODUTO;

DELETE FROM PRODUTO 
WHERE COD_PRODUTO = 3;

-- Neste caso, uma exceção será lançada, violação da constraint que amarra o produto ao item da nota fiscal.
-- Não é possível excluir uma chave primária que tem dependências em chaves estrangeiras


INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('Teste', 'LT', 25.00);

DELETE FROM PRODUTO 
WHERE COD_PRODUTO = 4;

