USE VIAGEM_AEREA;

CREATE VIEW VOOS_DETALHADOS AS
SELECT
    V.ID AS ID_VOO,
    AO.NOME AS AeroportoOrigem,
    AO.CIDADE AS CidadeOrigem,
    AO.UF AS UFOrigem,
    AD.NOME AS AeroportoDestino,
    AD.CIDADE AS CidadeDestino,
    AD.UF AS UFDestino,
    V.HORARIO_PREVISTO_SAIDA,
    V.HORARIO_SAIDA,
    V.HORARIO_PREVISTO_CHEGADA,
    V.HORARIO_CHEGADA
FROM
    VOO V
INNER JOIN
    AEROPORTO AO ON V.ID_AEROPORTO_ORIGEM = AO.ID
INNER JOIN
    AEROPORTO AD ON V.ID_AEROPORTO_DESTINO = AD.ID;

SELECT * FROM VOOS_DETALHADOS;

CREATE VIEW RESERVAS_CLIENTES AS
SELECT 
	C.ID AS IDCLIENTE,
	C.CPF,
	C.NOME,
	C.TELEFONE,
	P.LOCALIZACAO,
	A.MODELO,
	AO.NOME AS AEROPORTO_ORIGEM,
	AD.NOME AS AEROPORTO_DESTINO	
FROM RESERVA R
INNER JOIN CLIENTE C ON R.ID_CLIENTE = C.ID
INNER JOIN POLTRONA P ON R.ID_POLTRONA = P.ID
INNER JOIN AERONAVE A ON P.ID_AERONAVE = A.ID
INNER JOIN VOO V ON R.ID_VOO = V.ID
INNER JOIN AEROPORTO AO ON V.ID_AEROPORTO_ORIGEM = AO.ID
INNER JOIN AEROPORTO AD ON V.ID_AEROPORTO_DESTINO = AD.ID;


SELECT * FROM RESERVAS_CLIENTES WHERE IDCLIENTE = 4;

CREATE VIEW AERONAVES_MAIS_UTILIZADAS AS
SELECT 
	MODELO, 
	COUNT(MODELO) AS QTD_TRAJETOS
FROM AERONAVE A
INNER JOIN TRAJETO T ON T.ID_AERONAVE = A.ID
GROUP BY A.ID
ORDER BY QTD_TRAJETOS DESC;


SELECT * FROM AERONAVES_MAIS_UTILIZADAS;


CREATE VIEW MESES_MAIS_RESERVADOS AS
SELECT 
	DATE_FORMAT(HORARIO_PREVISTO_SAIDA, '%M') AS MES,
	COUNT(R.ID) AS QTD_RESERVAS
FROM VOO V
INNER JOIN RESERVA R ON V.ID = R.ID_VOO
GROUP BY MES
ORDER BY QTD_RESERVAS DESC
;

SELECT * 
FROM MESES_MAIS_RESERVADOS;
